USE BSTU;
GO

-- ALTER ADD: добавление столбца EMAIL
ALTER TABLE STUDENT
ADD EMAIL varchar(100) NULL;
GO

-- ALTER COLUMN: изменение типа столбца INFO
ALTER TABLE STUDENT
ALTER COLUMN INFO varchar(max);
GO

-- CONSTRAINT: значение по умолчанию для EMAIL
ALTER TABLE STUDENT
ADD CONSTRAINT STUDENT_EMAIL_DEFAULT DEFAULT 'no_email@bstu.ru' FOR EMAIL;
GO

-- ALTER DROP: удаление столбца FOTO
ALTER TABLE STUDENT
DROP COLUMN FOTO;
GO
